name: library_kelaniya   
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.10
  url_launcher: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_pro: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/carousel1.jpg
    - assets/carousel2.webp
    - assets/carousel3.jpg
    - assets/carousel4.jfif
    - assets/services/e_databases.png
    - assets/services/e_resources.png
    - assets/services/full_text.jpg
    - assets/services/library_services.jpg
    - assets/services/past_papers.png
    - assets/ReplaceAbout.jpg
    - assets/small.jpg
    - assets/kelaniya.png
 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
